"""Task implementations grouped into logical submodules."""

from .analysis import (
    AddLibraryTask,
    BuscoTask,
    BatchBuscoTask,
    DownloadBuscoLibraryTask,
    OrthoFinderTask,
    CreateProteomeBlastDB,
    ConstructBuscoBlastDB,
    ParalogRemovalTask,
    Decontamination,
    InternalDecontaminationTask,
    ExternalDecontaminationCheckTask,
    ExternalDecontaminationApplyTask,
    ImportCustomLibraryTask,
    MafftTask,
    IQTreeTask,
    BuildBuscoTreesTask,
    AnnotateOrthogroupTreeTask,
)
from .download import (
    DownloadAssembliesTask,
    ExampleTask,
    ImportLocalAssemblyTask,
    UpdateAssemblyInformation,
    BatchImportLocalAssemblyTask,
)
from .verify import (
    VerifyTask,
    VerifyAssemblyTask,
    VerifyBuscoTask,
    VerifyLibrariesTask,
    VerifyOrthofinderTask,
    VerifyDownloadsTask,
    SplitRecordsTask,
)
from .misc import CreateTaxonomyDB, FinalizeGenomeMoveTask, GenerateLineageCsvTask, ExportLibraryTask
from .cleanup import PrepareProteomeTask

__all__ = [
    "AddLibraryTask",
    "ImportCustomLibraryTask",
    "BuscoTask",
    "DownloadAssembliesTask",
    "DownloadBuscoLibraryTask",
    "ExampleTask",
    "ExportLibraryTask",
    "BatchImportLocalAssemblyTask",
    "ImportLocalAssemblyTask",
    "OrthoFinderTask",
    "UpdateAssemblyInformation",
    "CreateTaxonomyDB",
    "FinalizeGenomeMoveTask",
    "GenerateLineageCsvTask",
    "BatchBuscoTask",
    "CreateProteomeBlastDB",
    "ParalogRemovalTask",
    "Decontamination",
    "InternalDecontaminationTask",
    "ExternalDecontaminationCheckTask",
    "ExternalDecontaminationApplyTask",
    "ConstructBuscoBlastDB",
    "MafftTask",
    "IQTreeTask",
    "BuildBuscoTreesTask",
    "AnnotateOrthogroupTreeTask",
    "VerifyTask",
    "VerifyAssemblyTask",
    "VerifyDownloadsTask",
    "VerifyBuscoTask",
    "VerifyLibrariesTask",
    "VerifyOrthofinderTask",
    "SplitRecordsTask",
    "PrepareProteomeTask",
]
